### ISSUE TITLE
how can I change voice?

### ISSUE THREAD

**Issue by hansolGib** [QuyAnh2005/vits-japanese#1]
this is really interesting TTS. I'm trying to change the voice, but how can I achieve it?
I tried to record my voice reading BASIC5000_0001 and 0002, and I put them in jp_dataset/basic5000/wav folder.
and then I tried to run `python3 train.py -c configs/jp_base.json -m jp_base` this command in my Macbook
but I got an error `File "/Users/hansol/Downloads/vits-japanese-main/train.py", line 43, in main
    assert torch.cuda.is_available(), "CPU training is not allowed."` I guess it's because I'm using MacBook?. and I would like to confirm that this is the correct way to change the voice of TTS.

**Comment by QuyAnh2005** [comment]
@hansolGib Error `File "/Users/hansol/Downloads/vits-japanese-main/train.py", line 43, in main assert torch.cuda.is_available(), "CPU training is not allowed."` occured because the training process is required to use GPU (not use CPU - You are using CPU for training) 
Morever, if you are trying to change the voice by yourself, you need a lot of audios to train (often more 2 hours). An alternative way is that you should use TTS, then use a Voice Conversion system such as:
- [FragmentVC](https://github.com/QuyAnh2005/FragmentVC-Japanese) - not realtime
- styleTTS-VC (I will upload in the future) - realtime

Hope that it helps you.

**Comment by QuyAnh2005** [comment]
@hansolGib StyleTTS-VC for Japanese is available now at [here](https://github.com/QuyAnh2005/StyleTTS-VC-Japanese)
